"""Workload data models for concrete benchmark configurations."""

from __future__ import annotations

from typing import Literal, Optional, Union

from pydantic import Field, model_validator

from .base_model import BaseModelWithDocstrings, NonEmptyString, NonNegativeInt


class RandomInput(BaseModelWithDocstrings):
    """Random input generation descriptor."""

    type: Literal["random"] = "random"


class ScalarInput(BaseModelWithDocstrings):
    """Scalar literal input specification."""

    type: Literal["scalar"] = "scalar"
    value: Union[int, float, bool]


class SafetensorsInput(BaseModelWithDocstrings):
    """Input specification for data loaded from safetensors files."""

    type: Literal["safetensors"] = "safetensors"
    path: NonEmptyString
    tensor_key: NonEmptyString


class CustomInput(BaseModelWithDocstrings):
    """Custom input specification for inputs generated by reference code."""

    type: Literal["custom"] = "custom"


InputSpec = Union[RandomInput, SafetensorsInput, ScalarInput, CustomInput]


class ToleranceSpec(BaseModelWithDocstrings):
    """Tolerance specification for correctness checking."""

    max_atol: float = Field(default=1e-2)
    max_rtol: float = Field(default=1e-2)
    required_matched_ratio: float = Field(default=0.99)
    max_error_cap: Optional[float] = Field(default=None)
    allow_negative_inf: bool = Field(default=False)


class Workload(BaseModelWithDocstrings):
    """Concrete workload configuration for benchmarking."""

    axes: dict[str, NonNegativeInt]
    inputs: dict[str, InputSpec]
    uuid: NonEmptyString
    tolerance: ToleranceSpec = Field(default_factory=ToleranceSpec)

    @model_validator(mode="after")
    def _validate_inputs(self) -> "Workload":
        """Validate that workload doesn't mix custom and non-custom inputs."""
        custom_inputs = [
            name for name, inp in self.inputs.items() if isinstance(inp, CustomInput)
        ]
        non_custom_inputs = [
            name for name, inp in self.inputs.items() if not isinstance(inp, CustomInput)
        ]
        if len(custom_inputs) > 0 and len(non_custom_inputs) > 0:
            raise ValueError(
                f"A workload cannot have both custom and non-custom inputs. "
                f"Custom: {custom_inputs}. Non-custom: {non_custom_inputs}"
            )
        return self

    def get_scalar_inputs(self) -> dict[str, Union[int, float, bool]]:
        """Get all scalar input values."""
        return {
            name: inp.value
            for name, inp in self.inputs.items()
            if isinstance(inp, ScalarInput)
        }
